from __future__ import annotations

from app.web import runtime_process_history as web_runtime_process_history
from app.web import runtime_process_parsing as web_runtime_process_parsing


redact_command_secrets = web_runtime_process_parsing.redact_command_secrets
is_nmap_command = web_runtime_process_parsing.is_nmap_command
is_nuclei_command = web_runtime_process_parsing.is_nuclei_command
is_tshark_passive_capture_command = web_runtime_process_parsing.is_tshark_passive_capture_command
sample_process_tree_activity = web_runtime_process_parsing.sample_process_tree_activity
process_tree_activity_changed = web_runtime_process_parsing.process_tree_activity_changed
coerce_float = web_runtime_process_parsing.coerce_float
format_duration_label = web_runtime_process_parsing.format_duration_label
normalize_progress_source_label = web_runtime_process_parsing.normalize_progress_source_label
build_process_progress_payload = web_runtime_process_parsing.build_process_progress_payload
process_progress_adapter_for_command = web_runtime_process_parsing.process_progress_adapter_for_command
estimate_remaining_from_percent = web_runtime_process_parsing.estimate_remaining_from_percent
extract_progress_line = web_runtime_process_parsing.extract_progress_line
extract_nmap_progress_message = web_runtime_process_parsing.extract_nmap_progress_message
extract_nuclei_progress_from_text = web_runtime_process_parsing.extract_nuclei_progress_from_text
extract_tshark_passive_progress = web_runtime_process_parsing.extract_tshark_passive_progress
update_process_progress = web_runtime_process_parsing.update_process_progress
update_nmap_process_progress = web_runtime_process_parsing.update_nmap_process_progress
extract_nmap_progress_from_text = web_runtime_process_parsing.extract_nmap_progress_from_text
parse_duration_seconds = web_runtime_process_parsing.parse_duration_seconds

list_processes = web_runtime_process_history.list_processes
process_history_records = web_runtime_process_history.process_history_records
normalize_process_timestamp_to_utc = web_runtime_process_history.normalize_process_timestamp_to_utc
process_timestamp_utc_candidates = web_runtime_process_history.process_timestamp_utc_candidates
normalize_process_time_range_to_utc = web_runtime_process_history.normalize_process_time_range_to_utc
