from __future__ import annotations

from app.web import runtime_scheduler_excerpt as web_runtime_scheduler_excerpt
from app.web import runtime_scheduler_summary as web_runtime_scheduler_summary
from app.web import runtime_scheduler_target_context as web_runtime_scheduler_target_context


truncate_scheduler_text = web_runtime_scheduler_excerpt.truncate_scheduler_text
scheduler_output_lines = web_runtime_scheduler_excerpt.scheduler_output_lines
scheduler_line_signal_score = web_runtime_scheduler_excerpt.scheduler_line_signal_score
build_scheduler_excerpt = web_runtime_scheduler_excerpt.build_scheduler_excerpt
build_scheduler_prompt_excerpt = web_runtime_scheduler_excerpt.build_scheduler_prompt_excerpt
build_scheduler_analysis_excerpt = web_runtime_scheduler_excerpt.build_scheduler_analysis_excerpt
scheduler_tool_alias_tokens = web_runtime_scheduler_excerpt.scheduler_tool_alias_tokens
extract_unavailable_tool_tokens = web_runtime_scheduler_excerpt.extract_unavailable_tool_tokens
extract_missing_nse_script_tokens = web_runtime_scheduler_excerpt.extract_missing_nse_script_tokens
looks_like_local_tool_dependency_failure = web_runtime_scheduler_excerpt.looks_like_local_tool_dependency_failure
scheduler_banner_from_evidence = web_runtime_scheduler_excerpt.scheduler_banner_from_evidence
scheduler_service_banner_fallback = web_runtime_scheduler_excerpt.scheduler_service_banner_fallback

build_scheduler_context_summary = web_runtime_scheduler_summary.build_scheduler_context_summary
build_scheduler_coverage_summary = web_runtime_scheduler_summary.build_scheduler_coverage_summary

extract_scheduler_signals = web_runtime_scheduler_target_context.extract_scheduler_signals
build_scheduler_target_context = web_runtime_scheduler_target_context.build_scheduler_target_context
