from __future__ import annotations

from app.scheduler.state import get_target_state
from app.web import runtime_scheduler_ai_state as web_runtime_scheduler_ai_state
from app.web import runtime_scheduler_capture as web_runtime_scheduler_capture
from app.web import runtime_scheduler_inference as web_runtime_scheduler_inference
from app.web import runtime_scheduler_target_state as web_runtime_scheduler_target_state


CPE22_TOKEN_RE = web_runtime_scheduler_inference.CPE22_TOKEN_RE
CPE23_TOKEN_RE = web_runtime_scheduler_inference.CPE23_TOKEN_RE
CVE_TOKEN_RE = web_runtime_scheduler_inference.CVE_TOKEN_RE
TECH_VERSION_RE = web_runtime_scheduler_inference.TECH_VERSION_RE
REFERENCE_ONLY_FINDING_RE = web_runtime_scheduler_inference.REFERENCE_ONLY_FINDING_RE
ANSI_ESCAPE_RE = web_runtime_scheduler_inference.ANSI_ESCAPE_RE
IPV4_LIKE_RE = web_runtime_scheduler_inference.IPV4_LIKE_RE
TECH_CPE_HINTS = web_runtime_scheduler_inference.TECH_CPE_HINTS
WEAK_TECH_NAME_TOKENS = web_runtime_scheduler_inference.WEAK_TECH_NAME_TOKENS
TECH_STRONG_EVIDENCE_MARKERS = web_runtime_scheduler_inference.TECH_STRONG_EVIDENCE_MARKERS
PSEUDO_TECH_NAME_TOKENS = web_runtime_scheduler_inference.PSEUDO_TECH_NAME_TOKENS
GENERIC_TECH_NAME_TOKENS = web_runtime_scheduler_inference.GENERIC_TECH_NAME_TOKENS
AI_HOST_UPDATE_MIN_CONFIDENCE = web_runtime_scheduler_inference.AI_HOST_UPDATE_MIN_CONFIDENCE

ai_confidence_value = web_runtime_scheduler_inference.ai_confidence_value
sanitize_ai_hostname = web_runtime_scheduler_inference.sanitize_ai_hostname
extract_cpe_tokens = web_runtime_scheduler_inference.extract_cpe_tokens
extract_version_token = web_runtime_scheduler_inference.extract_version_token
is_ipv4_like = web_runtime_scheduler_inference.is_ipv4_like
sanitize_technology_version = web_runtime_scheduler_inference.sanitize_technology_version
sanitize_technology_version_for_tech = web_runtime_scheduler_inference.sanitize_technology_version_for_tech
observation_text_for_analysis = web_runtime_scheduler_inference.observation_text_for_analysis
technology_hint_source_text = web_runtime_scheduler_inference.technology_hint_source_text
cve_evidence_lines = web_runtime_scheduler_inference.cve_evidence_lines
extract_version_near_tokens = web_runtime_scheduler_inference.extract_version_near_tokens
normalize_cpe_token = web_runtime_scheduler_inference.normalize_cpe_token
cpe_base = web_runtime_scheduler_inference.cpe_base
is_weak_technology_name = web_runtime_scheduler_inference.is_weak_technology_name
technology_canonical_key = web_runtime_scheduler_inference.technology_canonical_key
technology_quality_score = web_runtime_scheduler_inference.technology_quality_score
name_from_cpe = web_runtime_scheduler_inference.name_from_cpe
version_from_cpe = web_runtime_scheduler_inference.version_from_cpe
guess_technology_hints = web_runtime_scheduler_inference.guess_technology_hints
guess_technology_hint = web_runtime_scheduler_inference.guess_technology_hint
severity_from_text = web_runtime_scheduler_inference.severity_from_text
finding_sort_key = web_runtime_scheduler_inference.finding_sort_key
is_placeholder_scheduler_text = web_runtime_scheduler_inference.is_placeholder_scheduler_text
infer_technologies_from_observations = web_runtime_scheduler_inference.infer_technologies_from_observations
infer_host_technologies = web_runtime_scheduler_inference.infer_host_technologies
normalize_ai_technologies = web_runtime_scheduler_inference.normalize_ai_technologies
merge_technologies = web_runtime_scheduler_inference.merge_technologies
infer_findings_from_observations = web_runtime_scheduler_inference.infer_findings_from_observations
infer_host_findings = web_runtime_scheduler_inference.infer_host_findings
infer_urls_from_observations = web_runtime_scheduler_inference.infer_urls_from_observations
infer_host_urls = web_runtime_scheduler_inference.infer_host_urls
normalize_ai_findings = web_runtime_scheduler_inference.normalize_ai_findings
normalize_ai_manual_tests = web_runtime_scheduler_inference.normalize_ai_manual_tests
merge_ai_items = web_runtime_scheduler_inference.merge_ai_items

persist_scheduler_ai_analysis = web_runtime_scheduler_ai_state.persist_scheduler_ai_analysis
persist_scheduler_reflection_analysis = web_runtime_scheduler_ai_state.persist_scheduler_reflection_analysis
apply_ai_host_updates = web_runtime_scheduler_ai_state.apply_ai_host_updates
enrich_host_from_observed_results = web_runtime_scheduler_ai_state.enrich_host_from_observed_results

queue_scheduler_approval = web_runtime_scheduler_capture.queue_scheduler_approval
record_scheduler_decision = web_runtime_scheduler_capture.record_scheduler_decision
build_scheduler_credential_row = web_runtime_scheduler_capture.build_scheduler_credential_row
build_scheduler_session_row = web_runtime_scheduler_capture.build_scheduler_session_row
extract_credential_capture_entries = web_runtime_scheduler_capture.extract_credential_capture_entries
persist_credential_captures_to_scheduler = web_runtime_scheduler_capture.persist_credential_captures_to_scheduler
persist_credential_capture_output = web_runtime_scheduler_capture.persist_credential_capture_output

coverage_gaps_from_summary = web_runtime_scheduler_target_state.coverage_gaps_from_summary
normalize_command_signature_source = web_runtime_scheduler_target_state.normalize_command_signature_source
command_signature_for_target = web_runtime_scheduler_target_state.command_signature_for_target
target_attempt_matches = web_runtime_scheduler_target_state.target_attempt_matches
persist_shared_target_state = web_runtime_scheduler_target_state.persist_shared_target_state
load_host_ai_analysis = web_runtime_scheduler_target_state.load_host_ai_analysis
scan_history_targets = web_runtime_scheduler_target_state.scan_history_targets


def existing_attempt_summary_for_target(runtime, host_id: int, host_ip: str, port: str, protocol: str):
    return web_runtime_scheduler_target_state.existing_attempt_summary_for_target(
        runtime,
        host_id,
        host_ip,
        port,
        protocol,
        get_target_state_fn=get_target_state,
    )


def existing_tool_attempts_for_target(runtime, host_id: int, host_ip: str, port: str, protocol: str):
    return web_runtime_scheduler_target_state.existing_tool_attempts_for_target(
        runtime,
        host_id,
        host_ip,
        port,
        protocol,
        get_target_state_fn=get_target_state,
    )
