from __future__ import annotations

from app.web import runtime_scheduler_host_inference as web_runtime_scheduler_host_inference
from app.web import runtime_scheduler_inference_helpers as web_runtime_scheduler_inference_helpers
from app.web import runtime_scheduler_observation_inference as web_runtime_scheduler_observation_inference


CPE22_TOKEN_RE = web_runtime_scheduler_inference_helpers.CPE22_TOKEN_RE
CPE23_TOKEN_RE = web_runtime_scheduler_inference_helpers.CPE23_TOKEN_RE
CVE_TOKEN_RE = web_runtime_scheduler_inference_helpers.CVE_TOKEN_RE
TECH_VERSION_RE = web_runtime_scheduler_inference_helpers.TECH_VERSION_RE
REFERENCE_ONLY_FINDING_RE = web_runtime_scheduler_inference_helpers.REFERENCE_ONLY_FINDING_RE
ANSI_ESCAPE_RE = web_runtime_scheduler_inference_helpers.ANSI_ESCAPE_RE
IPV4_LIKE_RE = web_runtime_scheduler_inference_helpers.IPV4_LIKE_RE
TECH_CPE_HINTS = web_runtime_scheduler_inference_helpers.TECH_CPE_HINTS
WEAK_TECH_NAME_TOKENS = web_runtime_scheduler_inference_helpers.WEAK_TECH_NAME_TOKENS
TECH_STRONG_EVIDENCE_MARKERS = web_runtime_scheduler_inference_helpers.TECH_STRONG_EVIDENCE_MARKERS
PSEUDO_TECH_NAME_TOKENS = web_runtime_scheduler_inference_helpers.PSEUDO_TECH_NAME_TOKENS
GENERIC_TECH_NAME_TOKENS = web_runtime_scheduler_inference_helpers.GENERIC_TECH_NAME_TOKENS
AI_HOST_UPDATE_MIN_CONFIDENCE = web_runtime_scheduler_inference_helpers.AI_HOST_UPDATE_MIN_CONFIDENCE

ai_confidence_value = web_runtime_scheduler_inference_helpers.ai_confidence_value
sanitize_ai_hostname = web_runtime_scheduler_inference_helpers.sanitize_ai_hostname
extract_cpe_tokens = web_runtime_scheduler_inference_helpers.extract_cpe_tokens
extract_version_token = web_runtime_scheduler_inference_helpers.extract_version_token
is_ipv4_like = web_runtime_scheduler_inference_helpers.is_ipv4_like
sanitize_technology_version = web_runtime_scheduler_inference_helpers.sanitize_technology_version
sanitize_technology_version_for_tech = web_runtime_scheduler_inference_helpers.sanitize_technology_version_for_tech
observation_text_for_analysis = web_runtime_scheduler_inference_helpers.observation_text_for_analysis
technology_hint_source_text = web_runtime_scheduler_inference_helpers.technology_hint_source_text
cve_evidence_lines = web_runtime_scheduler_inference_helpers.cve_evidence_lines
extract_version_near_tokens = web_runtime_scheduler_inference_helpers.extract_version_near_tokens
normalize_cpe_token = web_runtime_scheduler_inference_helpers.normalize_cpe_token
cpe_base = web_runtime_scheduler_inference_helpers.cpe_base
is_weak_technology_name = web_runtime_scheduler_inference_helpers.is_weak_technology_name
technology_canonical_key = web_runtime_scheduler_inference_helpers.technology_canonical_key
technology_quality_score = web_runtime_scheduler_inference_helpers.technology_quality_score
name_from_cpe = web_runtime_scheduler_inference_helpers.name_from_cpe
version_from_cpe = web_runtime_scheduler_inference_helpers.version_from_cpe
guess_technology_hints = web_runtime_scheduler_inference_helpers.guess_technology_hints
guess_technology_hint = web_runtime_scheduler_inference_helpers.guess_technology_hint
severity_from_text = web_runtime_scheduler_inference_helpers.severity_from_text
finding_sort_key = web_runtime_scheduler_inference_helpers.finding_sort_key
is_placeholder_scheduler_text = web_runtime_scheduler_inference_helpers.is_placeholder_scheduler_text
normalize_ai_technologies = web_runtime_scheduler_inference_helpers.normalize_ai_technologies
merge_technologies = web_runtime_scheduler_inference_helpers.merge_technologies
normalize_ai_findings = web_runtime_scheduler_inference_helpers.normalize_ai_findings
normalize_ai_manual_tests = web_runtime_scheduler_inference_helpers.normalize_ai_manual_tests
merge_ai_items = web_runtime_scheduler_inference_helpers.merge_ai_items

infer_technologies_from_observations = web_runtime_scheduler_observation_inference.infer_technologies_from_observations
infer_findings_from_observations = web_runtime_scheduler_observation_inference.infer_findings_from_observations
infer_urls_from_observations = web_runtime_scheduler_observation_inference.infer_urls_from_observations

infer_host_technologies = web_runtime_scheduler_host_inference.infer_host_technologies
infer_host_findings = web_runtime_scheduler_host_inference.infer_host_findings
infer_host_urls = web_runtime_scheduler_host_inference.infer_host_urls
