from __future__ import annotations

from app.web import runtime_project_bundle_archive as web_runtime_project_bundle_archive
from app.web import runtime_project_bundle_export as web_runtime_project_bundle_export
from app.web import runtime_project_bundle_rebase as web_runtime_project_bundle_rebase
from app.web import runtime_project_bundle_restore as web_runtime_project_bundle_restore


build_project_bundle_zip = web_runtime_project_bundle_export.build_project_bundle_zip
zip_add_file_if_exists = web_runtime_project_bundle_export.zip_add_file_if_exists
zip_add_dir_if_exists = web_runtime_project_bundle_export.zip_add_dir_if_exists

start_restore_project_zip_job = web_runtime_project_bundle_restore.start_restore_project_zip_job
restore_project_bundle_zip = web_runtime_project_bundle_restore.restore_project_bundle_zip
restore_project_bundle_zip_job = web_runtime_project_bundle_restore.restore_project_bundle_zip_job
restore_project_bundle_zip_impl = web_runtime_project_bundle_restore.restore_project_bundle_zip_impl
normalize_restore_compare_path = web_runtime_project_bundle_rebase.normalize_restore_compare_path
looks_like_absolute_path = web_runtime_project_bundle_rebase.looks_like_absolute_path
path_tail = web_runtime_project_bundle_rebase.path_tail
build_restore_root_mappings = web_runtime_project_bundle_rebase.build_restore_root_mappings
build_restore_text_replacements = web_runtime_project_bundle_rebase.build_restore_text_replacements
replace_restore_roots_in_text = web_runtime_project_bundle_rebase.replace_restore_roots_in_text
build_restore_basename_index = web_runtime_project_bundle_rebase.build_restore_basename_index
match_rebased_candidate = web_runtime_project_bundle_rebase.match_rebased_candidate
rebase_restored_file_reference = web_runtime_project_bundle_rebase.rebase_restored_file_reference
rewrite_restored_json_value = web_runtime_project_bundle_rebase.rewrite_restored_json_value
sqlite_table_columns = web_runtime_project_bundle_rebase.sqlite_table_columns
rewrite_restored_json_text = web_runtime_project_bundle_rebase.rewrite_restored_json_text
rewrite_sqlite_table_rows = web_runtime_project_bundle_rebase.rewrite_sqlite_table_rows
rebase_restored_project_paths = web_runtime_project_bundle_rebase.rebase_restored_project_paths
attach_restored_running_folder_locked = web_runtime_project_bundle_restore.attach_restored_running_folder_locked
extract_project_bundle_zip = web_runtime_project_bundle_archive.extract_project_bundle_zip
bundle_prefix = web_runtime_project_bundle_archive.bundle_prefix
safe_bundle_filename = web_runtime_project_bundle_archive.safe_bundle_filename
safe_bundle_relative_path = web_runtime_project_bundle_archive.safe_bundle_relative_path
read_bundle_manifest = web_runtime_project_bundle_archive.read_bundle_manifest
locate_bundle_session_member = web_runtime_project_bundle_archive.locate_bundle_session_member
extract_zip_member_to_file = web_runtime_project_bundle_archive.extract_zip_member_to_file
extract_zip_prefix_to_dir = web_runtime_project_bundle_archive.extract_zip_prefix_to_dir
normalize_existing_file = web_runtime_project_bundle_archive.normalize_existing_file
